name: "PR Review with Reply on Bot2"

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions: write-all

jobs:
  review-pr:
    if: |
      (github.event.issue.pull_request && (github.event.comment.in_reply_to_id != null || contains(github.event.comment.body, '/git-reply'))) ||
      (github.event_name == 'pull_request_review_comment')

    runs-on: ubuntu-latest

    steps:
      - name: Set Mode
        id: set_mode
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            echo "mode=reply" >> $GITHUB_OUTPUT
            echo "Mode: Reply to review comment"
          else
            echo "mode=review" >> $GITHUB_OUTPUT
            echo "Mode: Manual review triggered"
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ReviewReply/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install --cache-dir ~/.cache/pip -r ReviewReply/requirements.txt

      - name: Run GitHub Reviewer Logic
        run: |
          python ReviewReply/main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
          USE_VECTORSTORE: "true"
          MAX_LOOP: "2"
          MODE: ${{ steps.set_mode.outputs.mode }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
