name: "PR Review with GPT on Comment"

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  review-pr:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/git-review')
    runs-on: ubuntu-latest

    steps:
      - name: Log PR Info
        run: |
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Comment: ${{ github.event.comment.body }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitHub Reviewer Action
        uses: Rakeshreddysr2401/my-github-reviewer@Memory
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
          USE_VECTORSTORE: "true"
          MAX_LOOP: "2"

