# name: Claude Code Reviewer

# on:
#   issue_comment:
#     types: [created]
#   workflow_dispatch:

# permissions: write-all

# jobs:
#   claude-code-review:
#     runs-on: ubuntu-latest
#     if: |
#       github.event.issue.pull_request &&
#       contains(github.event.comment.body, '/claude-reviews')
#     steps:
#       - name: DEBUG - Log Context
#         run: |
#           echo "Comment: ${{ github.event.comment.body }}"
#           echo "Repo: ${{ github.repository }}"
#           echo "Issue Number: ${{ github.event.issue.number }}"
#           echo "Is PR: ${{ github.event.issue.pull_request != null }}"

#       - name: Checkout Repo
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Get PR SHAs
#         id: pr
#         run: |
#           PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
#           echo "head_sha=$(echo $PR_JSON | jq -r .head.sha)" >> $GITHUB_OUTPUT
#           echo "base_sha=$(echo $PR_JSON | jq -r .base.sha)" >> $GITHUB_OUTPUT
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - uses: Rakeshreddysr2401/ai-claude-code-reviewer@main
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#           EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
